services:
  wishlists-django:
    image: wishlists-django
    build: .
    command: ./entrypoint.sh compose
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
  db:
    image: postgres:18
    environment:
      - POSTGRES_DB=wishlists
      - POSTGRES_USER=wishlists
      - POSTGRES_PASSWORD=wishlists
    ports:
      - 5432:5432
